### PR TITLE
Change the way image data is stored

### PR DESCRIPTION
**Pull request by NikhilKalige**
#1 
1Band image returns (x, y)
Other images return (x, y, depth)

I just used the simplest method I could think of to change `_parse_tile_data` in `cubefile.py`. There could be better ways to do it.

### CODE REVIEW

**Comment by godber** [comment]
Note that the CI errors are pypy environment issues.  The tests pass in all other environments.  I am removing pypy from the tox file, we can add it back later.

I like the way this works, check out the notebook I worked with this morning:

http://nbviewer.ipython.org/urls/gist.githubusercontent.com/godber/dfb5d012fda603619ab9/raw/b1db599f53a5c468075ff854e9056698bd005cc7/gistfile1.json

Oh, note that in the example above I have one unmerged change that eliminates the `planetaryimage.pds3image` in imports.

So to @wtolson and @sbraden this branch changes the shape of the `data` attribute, which would disrupt existing Pysis users right?  The other issue is that the attribute `shape` no longer matches the `shape` of the array returned in `data` (look in notebook for shape).  I think I mentioned elsewhere that we could introduce a new attribute `image` that takes the desired shape and is the actual storage form of the data and have `data` do an on the fly conversion or something.

**Comment by godber** [comment]
Oh, now I remember @wtolson s suggestion to make it configurable.  We can set defaults at the subclass level and then provide the user a kwarg to change that default behaviour.  @NikhilKalige does this make sense?

**Comment by wtolson** [comment]
Yeah, pypy support will have to come when numpy is supported on pypy. You'll need to remove pypy from the TravisCI tests as well (in .travis.yml).

**Comment by NikhilKalige** [comment]
data is now configurable. You can change using `memory_layout` which takes `IMAGE` or `DISK`. 

Cublefile defaults to `DISK` and PDS3 to `IMAGE`

**Comment by godber** [comment]
OK, I am happy with how this worked out.  The `memory_layout` will remain the same for pysis users unless they explicitly change it.  `.shape` will match `.data.shape` in that case.  But for PDS images where the `memory_layout` is `IMAGE` `.shape` will not match `.data.shape`.  We can deal with that later.

**Pull request merged**
